application: rzdzstan0
version: 1
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "5d"

skip_files:
- ^(.*/)?.*\.py[co]

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /themes
  static_dir: themes

- url: /summary_mail
  script: web.app
  login: admin

- url: /.*
  script: web.app

libraries:
- name: webapp2
  version: "latest"

error_handlers:
  - file: /themes/default_error.html

  - error_code: over_quota
    file: /themesover_quota.html